export {default as Signup} from './signup/Signup'
export {default as Login} from './login/Login'
export {default as Home} from './home/Home'
export {default as Player} from './player/Player'
export {default as MyList} from './myList/MyList'
export {default as Movies} from './movies/Movies'
export {default as TVShows} from './tv/TVShows'